/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnakalypseRouteImport } from './routes/anakalypse'
import { Route as DimofiliRouteImport } from './routes/dimofili'
import { Route as KatigoriesRouteImport } from './routes/katigories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SxetikaRouteImport } from './routes/sxetika'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminPasswordRouteImport } from './routes/admin.password'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as ArthroSlugRouteImport } from './routes/arthro.$slug'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as EtiketaSlugRouteImport } from './routes/etiketa.$slug'
import { Route as KatigoriaSlugRouteImport } from './routes/katigoria.$slug'
import { Route as SyntaktisSlugRouteImport } from './routes/syntaktis.$slug'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as MediaDemoIdRouteImport } from './routes/media.demo.$id'
import { Route as AdminArticlesSlugEditRouteImport } from './routes/admin.articles.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnakalypseRoute = AnakalypseRouteImport.update({
  id: '/anakalypse',
  path: '/anakalypse',
  getParentRoute: () => rootRouteImport,
} as any)
const DimofiliRoute = DimofiliRouteImport.update({
  id: '/dimofili',
  path: '/dimofili',
  getParentRoute: () => rootRouteImport,
} as any)
const KatigoriesRoute = KatigoriesRouteImport.update({
  id: '/katigories',
  path: '/katigories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SxetikaRoute = SxetikaRouteImport.update({
  id: '/sxetika',
  path: '/sxetika',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasswordRoute = AdminPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const ArthroSlugRoute = ArthroSlugRouteImport.update({
  id: '/arthro/$slug',
  path: '/arthro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiketaSlugRoute = EtiketaSlugRouteImport.update({
  id: '/etiketa/$slug',
  path: '/etiketa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KatigoriaSlugRoute = KatigoriaSlugRouteImport.update({
  id: '/katigoria/$slug',
  path: '/katigoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntaktisSlugRoute = SyntaktisSlugRouteImport.update({
  id: '/syntaktis/$slug',
  path: '/syntaktis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const MediaDemoIdRoute = MediaDemoIdRouteImport.update({
  id: '/media/demo/$id',
  path: '/media/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesSlugEditRoute = AdminArticlesSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anakalypse': typeof AnakalypseRoute
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/login': typeof LoginRoute
  '/sxetika': typeof SxetikaRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/team': typeof AdminTeamRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/etiketa/$slug': typeof EtiketaSlugRoute
  '/katigoria/$slug': typeof KatigoriaSlugRoute
  '/syntaktis/$slug': typeof SyntaktisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/media/demo/$id': typeof MediaDemoIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anakalypse': typeof AnakalypseRoute
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/login': typeof LoginRoute
  '/sxetika': typeof SxetikaRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/team': typeof AdminTeamRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/etiketa/$slug': typeof EtiketaSlugRoute
  '/katigoria/$slug': typeof KatigoriaSlugRoute
  '/syntaktis/$slug': typeof SyntaktisSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/media/demo/$id': typeof MediaDemoIdRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anakalypse': typeof AnakalypseRoute
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/login': typeof LoginRoute
  '/sxetika': typeof SxetikaRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/team': typeof AdminTeamRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/etiketa/$slug': typeof EtiketaSlugRoute
  '/katigoria/$slug': typeof KatigoriaSlugRoute
  '/syntaktis/$slug': typeof SyntaktisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/media/demo/$id': typeof MediaDemoIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anakalypse'
    | '/dimofili'
    | '/katigories'
    | '/login'
    | '/sxetika'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/team'
    | '/arthro/$slug'
    | '/auth/confirm'
    | '/etiketa/$slug'
    | '/katigoria/$slug'
    | '/syntaktis/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/media/demo/$id'
    | '/admin/articles/'
    | '/admin/articles/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anakalypse'
    | '/dimofili'
    | '/katigories'
    | '/login'
    | '/sxetika'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/team'
    | '/arthro/$slug'
    | '/auth/confirm'
    | '/etiketa/$slug'
    | '/katigoria/$slug'
    | '/syntaktis/$slug'
    | '/admin'
    | '/admin/articles/new'
    | '/media/demo/$id'
    | '/admin/articles'
    | '/admin/articles/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anakalypse'
    | '/dimofili'
    | '/katigories'
    | '/login'
    | '/sxetika'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/team'
    | '/arthro/$slug'
    | '/auth/confirm'
    | '/etiketa/$slug'
    | '/katigoria/$slug'
    | '/syntaktis/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/media/demo/$id'
    | '/admin/articles/'
    | '/admin/articles/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnakalypseRoute: typeof AnakalypseRoute
  DimofiliRoute: typeof DimofiliRoute
  KatigoriesRoute: typeof KatigoriesRoute
  LoginRoute: typeof LoginRoute
  SxetikaRoute: typeof SxetikaRoute
  ArthroSlugRoute: typeof ArthroSlugRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  EtiketaSlugRoute: typeof EtiketaSlugRoute
  KatigoriaSlugRoute: typeof KatigoriaSlugRoute
  SyntaktisSlugRoute: typeof SyntaktisSlugRoute
  MediaDemoIdRoute: typeof MediaDemoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anakalypse': {
      id: '/anakalypse'
      path: '/anakalypse'
      fullPath: '/anakalypse'
      preLoaderRoute: typeof AnakalypseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimofili': {
      id: '/dimofili'
      path: '/dimofili'
      fullPath: '/dimofili'
      preLoaderRoute: typeof DimofiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katigories': {
      id: '/katigories'
      path: '/katigories'
      fullPath: '/katigories'
      preLoaderRoute: typeof KatigoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sxetika': {
      id: '/sxetika'
      path: '/sxetika'
      fullPath: '/sxetika'
      preLoaderRoute: typeof SxetikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/password': {
      id: '/admin/password'
      path: '/password'
      fullPath: '/admin/password'
      preLoaderRoute: typeof AdminPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/arthro/$slug': {
      id: '/arthro/$slug'
      path: '/arthro/$slug'
      fullPath: '/arthro/$slug'
      preLoaderRoute: typeof ArthroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiketa/$slug': {
      id: '/etiketa/$slug'
      path: '/etiketa/$slug'
      fullPath: '/etiketa/$slug'
      preLoaderRoute: typeof EtiketaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katigoria/$slug': {
      id: '/katigoria/$slug'
      path: '/katigoria/$slug'
      fullPath: '/katigoria/$slug'
      preLoaderRoute: typeof KatigoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syntaktis/$slug': {
      id: '/syntaktis/$slug'
      path: '/syntaktis/$slug'
      fullPath: '/syntaktis/$slug'
      preLoaderRoute: typeof SyntaktisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/media/demo/$id': {
      id: '/media/demo/$id'
      path: '/media/demo/$id'
      fullPath: '/media/demo/$id'
      preLoaderRoute: typeof MediaDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$slug/edit': {
      id: '/admin/articles/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/articles/$slug/edit'
      preLoaderRoute: typeof AdminArticlesSlugEditRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminArticlesSlugEditRoute: typeof AdminArticlesSlugEditRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminArticlesSlugEditRoute: AdminArticlesSlugEditRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPasswordRoute: typeof AdminPasswordRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPasswordRoute: AdminPasswordRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnakalypseRoute: AnakalypseRoute,
  DimofiliRoute: DimofiliRoute,
  KatigoriesRoute: KatigoriesRoute,
  LoginRoute: LoginRoute,
  SxetikaRoute: SxetikaRoute,
  ArthroSlugRoute: ArthroSlugRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  EtiketaSlugRoute: EtiketaSlugRoute,
  KatigoriaSlugRoute: KatigoriaSlugRoute,
  SyntaktisSlugRoute: SyntaktisSlugRoute,
  MediaDemoIdRoute: MediaDemoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
