/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnakalyChar968Char949RouteImport } from './routes/anakalyψε'
import { Route as DimofiliRouteImport } from './routes/dimofili'
import { Route as KatigoriesRouteImport } from './routes/katigories'
import { Route as SxetikaRouteImport } from './routes/sxetika'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArthroSlugRouteImport } from './routes/arthro.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnakalyChar968Char949Route = AnakalyChar968Char949RouteImport.update({
  id: '/anakalyψε',
  path: '/anakalyψε',
  getParentRoute: () => rootRouteImport,
} as any)
const DimofiliRoute = DimofiliRouteImport.update({
  id: '/dimofili',
  path: '/dimofili',
  getParentRoute: () => rootRouteImport,
} as any)
const KatigoriesRoute = KatigoriesRouteImport.update({
  id: '/katigories',
  path: '/katigories',
  getParentRoute: () => rootRouteImport,
} as any)
const SxetikaRoute = SxetikaRouteImport.update({
  id: '/sxetika',
  path: '/sxetika',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ArthroSlugRoute = ArthroSlugRouteImport.update({
  id: '/arthro/$slug',
  path: '/arthro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anakalyψε': typeof AnakalyChar968Char949Route
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/sxetika': typeof SxetikaRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anakalyψε': typeof AnakalyChar968Char949Route
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/sxetika': typeof SxetikaRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anakalyψε': typeof AnakalyChar968Char949Route
  '/dimofili': typeof DimofiliRoute
  '/katigories': typeof KatigoriesRoute
  '/sxetika': typeof SxetikaRoute
  '/arthro/$slug': typeof ArthroSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anakalyψε'
    | '/dimofili'
    | '/katigories'
    | '/sxetika'
    | '/arthro/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anakalyψε'
    | '/dimofili'
    | '/katigories'
    | '/sxetika'
    | '/arthro/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anakalyψε'
    | '/dimofili'
    | '/katigories'
    | '/sxetika'
    | '/arthro/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnakalyChar968Char949Route: typeof AnakalyChar968Char949Route
  DimofiliRoute: typeof DimofiliRoute
  KatigoriesRoute: typeof KatigoriesRoute
  SxetikaRoute: typeof SxetikaRoute
  ArthroSlugRoute: typeof ArthroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anakalyψε': {
      id: '/anakalyψε'
      path: '/anakalyψε'
      fullPath: '/anakalyψε'
      preLoaderRoute: typeof AnakalyChar968Char949RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimofili': {
      id: '/dimofili'
      path: '/dimofili'
      fullPath: '/dimofili'
      preLoaderRoute: typeof DimofiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katigories': {
      id: '/katigories'
      path: '/katigories'
      fullPath: '/katigories'
      preLoaderRoute: typeof KatigoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sxetika': {
      id: '/sxetika'
      path: '/sxetika'
      fullPath: '/sxetika'
      preLoaderRoute: typeof SxetikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/arthro/$slug': {
      id: '/arthro/$slug'
      path: '/arthro/$slug'
      fullPath: '/arthro/$slug'
      preLoaderRoute: typeof ArthroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnakalyChar968Char949Route: AnakalyChar968Char949Route,
  DimofiliRoute: DimofiliRoute,
  KatigoriesRoute: KatigoriesRoute,
  SxetikaRoute: SxetikaRoute,
  ArthroSlugRoute: ArthroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
